### ISSUE TITLE
One line build failure - curl output

### ISSUE THREAD

**Issue by johnvanlowe** [joshuacox/reactionetes#27]
(ctrl-c now to stop if this is not what you intend)!!!!!
--
Cloning the latest reactionetes repo
Cloning into 'reactionetes'...
remote: Counting objects: 78, done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 78 (delta 22), reused 34 (delta 6), pack-reused 0
Unpacking objects: 100% (78/78), done.
Checking connectivity... done.
Adjusting dotfiles
Adjusting dotfiles
make[1]: Entering directory '/tmp/tmp.GoDupSq3O1.reactionetes/reactionetes'
make[1]: '/root/.r8s/bin/minikube' is up to date.
make[1]: Leaving directory '/tmp/tmp.GoDupSq3O1.reactionetes/reactionetes'
make[1]: Entering directory '/tmp/tmp.GoDupSq3O1.reactionetes/reactionetes'
make[1]: '/root/.r8s/bin/kubectl' is up to date.
make[1]: Leaving directory '/tmp/tmp.GoDupSq3O1.reactionetes/reactionetes'
bash: line 24: type: kubectl: not found
-------------------------------------------------------------

  
ERROR!!!  --  
kubectl was not found in your path!
To proceed please install kubectl to your path and try again!

**Comment by joshuacox** [comment]
A few things here, try as non root, I've tidied up some of the dotfiles issues as well for default ubuntu and some others.  Try again, and re-open if you get the same results.
